services:
  - type: web
    name: envelope-fullstack
    env: node
    plan: free
    rootDir: ./
    buildCommand: |
      npm install
      npm run build -- --configuration production
    startCommand: npm start